### ISSUE TITLE
BSgate (and so 2-mode squeezing) probably incorrect

### ISSUE THREAD

**Issue by ziofil** [XanaduAI/strawberryfields#186] opened 2019-09-16 11:48 UTC
This should be an identity operator, no?

```python
prog = sf.Program(num_subsystems=2)
with prog.context as q:
    ops.S2gate(0.0, 0.0) | (q[0], q[1])
    
S = utils.extract_unitary(prog, cutoff_dim=4, backend='fock')
plt.matshow(abs(np.einsum('acbd', S).reshape((16,16))))
```

<img width="266" alt="Capture d’écran 2019-09-16 à 13 22 44" src="https://user-images.githubusercontent.com/8944955/64954184-1a007b80-d885-11e9-9346-4a8f937d36c9.png">

I suspect that the problem is in the BSgate, which is the one you use to define the S2gate (I checked the single-mode squeezing and it seems OK to me)

```python
prog = sf.Program(num_subsystems=2)
with prog.context as q:
    ops.BSgate(-np.pi/4, 0.0) | (q[0], q[1])
    ops.BSgate(np.pi/4, 0.0) | (q[0], q[1])
    
BS = utils.extract_unitary(prog, cutoff_dim=4, backend='fock')
plt.matshow(abs(np.einsum('acbd', BS).reshape((16,16))))
```
<img width="266" alt="Capture d’écran 2019-09-16 à 13 22 44" src="https://user-images.githubusercontent.com/8944955/64954184-1a007b80-d885-11e9-9346-4a8f937d36c9.png">

**Comment by co9olguy** [comment] 2019-09-16 15:22
Thanks @ziofil. We will take a look.

Do you see the same behaviour for all three backends, or is it backend-specific?

**Comment by co9olguy** [comment] 2019-09-16 15:23
Also, are you able to produce a bug without using the `extract_unitary` function? Just trying to minimize the (possible) sources of error

**Comment by ziofil** [comment] 2019-09-16 15:26
This is the only backend that I checked

**Comment by josh146** [comment] 2019-09-16 15:28
I just ran @ziofil's minimal example --- looking at `state.cov()` for the Gaussian backend, and `state.ket()` for the Fock backend with a cutoff of 4, in both cases my output is the vacuum state

**Comment by ziofil** [comment] 2019-09-16 15:36
Yes because |0,0> is mapped to |0,0>. Try with |1,3> or |3,1>

**Comment by co9olguy** [comment] 2019-09-16 19:33
It's a bit unusual that it would give incorrect results for all three backends, considering there are two quite different representations being used :thinking:

**Comment by nquesada** [comment] 2019-09-16 19:35
The Gaussian backend cannot take as input |1,3>. I doubt that for valid inputs it gives wrong results.

**Comment by co9olguy** [comment] 2019-09-16 20:01
@ziofil I have the working hypothesis that the results you're seeing are numerical truncation issues. If I run this example:
```
eng = sf.Engine(backend="fock", backend_options={"cutoff_dim": 4})

prog = sf.Program(2)
with prog.context as q:
    ops.Fock(1) | q[0]
    ops.Fock(3) | q[1]
    ops.BSgate(-np.pi/4, 0.0) | (q[0], q[1])
    ops.BSgate(np.pi/4, 0.0) | (q[0], q[1])

results = eng.run(prog)

dm = results.state.dm()
```

I can confirm that the resulting density matrix is unphysical (not normalized). Specifically, the density matrix elements [1,1,3,3] and [3,3,1,1] are non-zero; they have values of 0.25. This leads to a trace of 0.5.

However, a simulation cutoff dimension of 4 means that only Fock states (0,1,2,3) in each mode will be captured. The (0,4) and (4,0) Fock states, which are possible to populate from these input states, will be missed. 

However, if I rerun the same example with `cutoff_dim=5`, the resulting density matrix is what we expect: only the [1,1,3,3] element is nonzero, and equal to one.

Are you seeing the same issue in a case where there is no ambiguity about the cutoff dimension relative to the inputs?

**Comment by ziofil** [comment] 2019-09-16 20:32
Exactly, for cutoff=4 amplitudes of up to 3 photons per mode should be there, but for |1,3> it gives the wrong numbers. (for cutoff=5 see |4,1>). I mean, just look at the unitary.
I suspect that it's a truncation issue (multiplying truncated matrices not in the LU order).

**Comment by co9olguy** [comment] 2019-09-16 20:38
Yes, that's my assessment. A single beamsplitter already "overflows" the cutoff dimension. Adding the reverse unitary doesn't correct this (but we could also merge gates before running program to fix that).

But I wouldn't classify this as a bug, more of an issue with numerical parameter choice.

**Comment by ziofil** [comment] 2019-09-16 20:40
Yes, the BS is not wrong. The 2-mode squeezing matrix elements are wrong, though. A possible solution would be to redefine `S2gate` on its own with some disentangling formula rather than via the BS.

**Comment by ziofil** [comment] 2019-09-16 20:42
If only we had the matrix elements of a general gaussian transformation 😁

**Comment by co9olguy** [comment] 2019-09-16 21:31
Two mode-squeezing is implemented as passive beamsplitters and energy-changing squeezing operations. The single-mode squeezing gate itself causes numerical errors (even without any beamsplitters) if squeezing is too high relative to cutoff. Again, this as a truncation problem. 

Closing this particular issue, as it seems not to be a bug, but rather due to a known drawback/tradeoff of numeric simulation

**Closed by co9olguy** 2019-09-16 21:31 UTC
Labels: bug

**Comment by nquesada** [comment] 2019-10-22 19:32
@ziofil: We do have the matrix elements of general Gaussian transformation
