### ISSUE TITLE
Improve the tensor(), partial_trace(), insert(), and similar methods to more efficiently deal with pure states

### ISSUE THREAD

**Issue by cgogolin** [XanaduAI/strawberryfields#20] opened 2018-07-08 11:48 UTC
This would improve performance and avoid code duplication. Some code for reordering modes could even  be written in a unified way for both the foch and tf backend and moved into a `base_ops.py`. This could prepare SF for a more intelligent handling of the purity of the internal state representation.

**Comment by co9olguy** [comment] 2018-07-09 14:02
Hi @cgogolin, this issue is a bit unclear to me. Can you provide some more specific points about what could be done here?

**Comment by josh146** [comment] 2019-03-07 00:58
As the backends are designed to be fully independent and (by design) do not share any code, I am closing this issue for now.

**Closed by josh146** 2019-03-07 00:58 UTC
Labels: enhancement
