### ISSUE TITLE
Error "Probabilities do not sum to 1" using GBS for simulating Vibronic Spectra of Pyrazine

### ISSUE THREAD

**Issue by wait-a-sec** [XanaduAI/strawberryfields#597] opened 2021-06-17 06:24 UTC
-------------------------------------------------------------------------------------------------------------

#### Issue description

While simulating the Vibronic Spectra of Pyrazine, I get the error "Probabilities do not sum to 1" when simulating all 24 modes. However when I use less than 3 or modes the code is able to execute. This error pops up not only in the case of large molecules or number of modes, but is present in the case of high number of samples as well. 
When simulating the spectra for Water, this error is present if the number of samples are taken to be 50,000.

[pyrazine_ground.log](https://github.com/XanaduAI/strawberryfields/files/6667817/pyrazine_ground.log)
[pyrazine_charged.log](https://github.com/XanaduAI/strawberryfields/files/6667818/pyrazine_charged.log)
![Screenshot (119)](https://user-images.githubusercontent.com/34483711/122342940-cd1e6d00-cf62-11eb-8030-07577d57d664.png)
![Screenshot (118)](https://user-images.githubusercontent.com/34483711/122342944-cee83080-cf62-11eb-8db6-920001cb3a5d.png)

**Comment by soranjh** [comment] 2021-06-17 13:40
Thanks @wait-a-sec. The issue might be resolved by renormalizing the probability vector, which in your examples is very likely smaller than one by a small margin. I will look into it and come back to you asap.

**Comment by co9olguy** [comment] 2021-08-14 19:25
Closing as this appears to have been fixed by https://github.com/XanaduAI/thewalrus/pull/250.
Feel free to reopen if the issue is not resolved

**Closed by co9olguy** 2021-08-14 19:25 UTC
